Correct filename in #include directive
ColorPresets.h was renamed to Palettes.h in aae6ee83df01b382cae442ee493e2b3a8ef44af3 but the #include directive was not updated to reflect this change. This caused compilation to fail:

ArduCor.cpp:16:26: fatal error: ColorPresets.h: No such file or directory